### ISSUE TITLE
bash compile

### ISSUE THREAD

**Issue by xia-xinmu** [peihanmiao/OPRF-PSI#1]
=================== Building Boost ===================
 https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.bz2  error 403：Forbidden。
how can i fix it? 
Thanks a lot.

**Comment by peihanmiao** [comment]
You could try to download it from here: https://boostorg.jfrog.io/artifactory/main/release/1.69.0/source/boost_1_69_0.tar.bz2

Let me know if it doesn't work.

Thanks,
Peihan

**Comment by xia-xinmu** [comment]
i have done it!
Thanks!
