### ISSUE TITLE
Failed to find boost

### ISSUE THREAD

**Issue by InnovationFlash** [peihanmiao/OPRF-PSI#2]
I change the dead link as the former issue does, but I got a new error in bashing the compile;

![1650271443(1)](https://user-images.githubusercontent.com/20762434/163782596-55b51c32-3c49-4e5f-a5c3-54e335cd386c.png)

my gcc's version is 11.2 and 9.6.

Does the boost's version must  newer than 1.66.0? Or must be 1.69.0;

I guess it is a problem of version ,but I dont get any useful solution.

Could you help me about that?

Thanks!

**Comment by peihanmiao** [comment]
Do you have the boost library compiled under the folder "../libOTe/cryptoTools/thirdparty/linux/boost/"? It seems the system couldn't find boost there. I'm not sure if the 1.66.0 version works.

**Comment by InnovationFlash** [comment]
> Do you have the boost library compiled under the folder "../libOTe/cryptoTools/thirdparty/linux/boost/"? It seems the system couldn't find boost there. I'm not sure if the 1.66.0 version works.

Thanks for your help.

I use the version 1.73.0 of the boost.

It seems like the boost thread module compiled incorrect.

But when I use newer version,simply use your bash to compile boost, it will lose some object file.

By the way,the warning in cmake can be ignored?

Thanks for your help.

**Comment by peihanmiao** [comment]
Glad to hear you figured it out :). Yes, the warnings can be ignored.

**Comment by InnovationFlash** [comment]
> Glad to hear you figured it out :). Yes, the warnings can be ignored.

Thank you :).

**Comment by Icanlove77** [comment]
Hi,I met the same issue with you,
the problem is  boost thread module compiled incorrect.
just add two lines in "thread_data.hpp"

#undef PTHREAD_STACK_MIN
#define PTHREAD_STACK_MIN 16384

it works perfect!

**Comment by ZhangChuanxin1** [comment]
Hi, I have the same problem: 

CMake Error at PSI/CMakeLists.txt:25 (message):

Failed to find boost at

Could you tell me how to solve this problem? I re-installed 1.74 boost library, but it still can't solve the problem.
